spring:
  messages:
    basename: locale/message
questions:
  file:
    path: data/
    template: questions
    extension: csv
locale:
  lang: ru
  country: RU
right:
  count: 3

datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:54321/postgres
    username: user
    password: password
