spring:
  datasource:
    url: jdbc:postgresql://${library.pgnodes}/${library.pgdb}?targetServerType=primary&currentSchema=${library.pgschema}
    username: ${library.pguser}
    password: ${library.pgpwd}
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml

library:
  pgnodes: localhost:5432
  pgdb: library
  pguser: postgres
  pgpwd: mysecretpassword
  pgschema: public

logging:
  level:
    root: ERROR