version: '3.7'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    privileged: true
    stdin_open: true
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=org.postgresql.Driver
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:54321/postgres
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=password
    networks:
      - nw
  postgres:
    image: "postgres:10.5"
    ports:
      - "54321:5432"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgres
    networks:
      - nw
networks:
  nw:
