FROM maven:3.5.4-jdk-11

ENV PROJECT_DIR=/opt/questionnaire

RUN mkdir -p $PROJECT_DIR

WORKDIR $PROJECT_DIR

ADD ./pom.xml $PROJECT_DIR

RUN mvn dependency:resolve

ADD ./src $PROJECT_DIR/src

RUN mvn install


FROM openjdk:11-jre-slim

ENV PROJECT_DIR=/opt/questionnaire

RUN mkdir -p $PROJECT_DIR

WORKDIR $PROJECT_DIR

COPY --from=0 $PROJECT_DIR/target/library* $PROJECT_DIR/

EXPOSE 8080

COPY target/questionnaire-1.0-SNAPSHOT.jar ./bin/questionnaire.jar

CMD ["java", "-jar", "./bin/questionnaire.jar"]
